# Generated by Django 5.2.4 on 2025-07-16 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text="A bit about yourself, your lifestyle, and what you're looking for.")),
                ('budget', models.DecimalField(decimal_places=2, help_text='Your estimated monthly budget for rent.', max_digits=8)),
                ('preferred_move_in_date', models.DateField(blank=True, null=True)),
                ('location_preference', models.CharField(blank=True, help_text='e.g., Downtown, near the university', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
