# Generated by Django 5.2.4 on 2025-07-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommateprofile',
            name='location_preference',
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='location',
            field=models.CharField(blank=True, help_text='e.g., Downtown, near the university', max_length=255),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
