# Generated by Django 5.2.4 on 2025-07-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
    ]
