# Generated by Django 5.2.4 on 2025-07-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_main_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Automatically generated from the location. Do not edit.', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.CharField(blank=True, help_text="E.g., 'Bijuli Bazar Near Kings College, 'Shakhamul' or 'UN Park'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Automatically generated from the location. Do not edit.', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='main_photo',
            field=models.ImageField(blank=True, help_text='The main photo for the listing.', null=True, upload_to='listings/'),
        ),
    ]
